### ISSUE TITLE
tdiary.orgをHerokuへ引っ越しする

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-org#15]
そろそろtdiary.orgもHerokuへ引っ越しして良さそうですが、どうでしょう。
コンテンツは移行済みなので、あとはDNSレコードを書き換えればWebは移行できます。

https://tdiary-org.herokuapp.com/

**Comment by tdtds** [comment]
BlogkitをベースにしたカスタムDockerイメージを作ってHerokuで動かすようにしました。
