### ISSUE TITLE
DNSを移転する

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-org#16]
実はDNSの運用をなんとかしたい(もう自前でBIND動かすのはイヤ)というのがあって、Herokuへの移行(#15)タイミングで一緒にやりたいと考えてました。多少の費用がかかるのはかまわないので、adminメンバで管理が共有できて継続性が期待できるDNSサービスに乗り換えたいです。

アイデア求む。

**Comment by hsbt** [comment]
個人的には route53 が API でぴっと使えて便利なんで、それでいいような気がしますが、アカウントの手間暇と数百円かかるってあたりですかねえ。

**Comment by machu** [comment]
僕はvalue domainで10年以上運用してます。柔軟に使えて継続性も大丈夫ですが、管理を共用したいという要件は満たさないです。
route53は使ったことないですが、共用できるならアリですね。

**Comment by machu** [comment]
DNSサーバだけでなく、ドメインを共同管理できるようにしないとですね。
逆に、ドメインだけ共同管理できていれば、DNSサーバは個人管理でもいいのかも。

**Comment by tdtds** [comment]
Cloudflareを使うようにしたので、DNSもCloudflareになっています。とりあえずclose。
