### ISSUE TITLE
絵日記プラグインのデータ移行

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-org#6]
日記本体はtdiary-mongodb-convertで移行できたが、絵日記プラグインは移行できていない。

**Comment by tdtds** [comment]
tDiary.Netでは過去に絵日記プラグインで書かれた日記は、image.rbを完全に差し替えて、別サーバにある画像のURLを差し込むものにしてあります。新しい物はpicasa.rbやflickr.rbを使ってもらう方針。

tDiary.orgの場合もそうするか、GitHub上のリポジトリに追加してしまってもいいかも?

**Comment by machu** [comment]
最近は画像をアップしていないので、 5654138 でGitHubのリポジトリに含めておきました。

**Comment by machu** [comment]
新しく画像をアップできない問題はありますが、移行はできたのでこのissueはクローズします。
